# ODTE Realistic Fill Execution Profiles
# Maps to realFillSimulationUpgrade.md specification

profiles:
  conservative:
    latency_ms: 250
    max_tob_participation: 0.05
    slippage_floor:
      per_contract: 0.02
      pct_of_spread: 0.10
    size_penalty:
      bp_per_extra_tob_multiple: 8
    adverse_selection_bps: 25
    mid_fill:
      p_when_spread_leq_20c:
        conservative: 0.00
        base: 0.15
        optimistic: 0.30
      p_otherwise:
        conservative: 0.00
        base: 0.05
        optimistic: 0.15
    event_overrides:
      open_close_window_minutes: 10
      set_mid_probability_to_zero: true
      specific_events:
        fomc:
          mid_acceptance_multiplier: 0.0
          spread_multiplier: 2.0
          latency_multiplier: 1.5
        cpi:
          mid_acceptance_multiplier: 0.0
          spread_multiplier: 1.8
          latency_multiplier: 1.3
        opex:
          mid_acceptance_multiplier: 0.5
          spread_multiplier: 1.3
          latency_multiplier: 1.1

  base:
    latency_ms: 200
    max_tob_participation: 0.08
    slippage_floor:
      per_contract: 0.02
      pct_of_spread: 0.08
    size_penalty:
      bp_per_extra_tob_multiple: 6
    adverse_selection_bps: 20
    mid_fill:
      p_when_spread_leq_20c:
        conservative: 0.00
        base: 0.15
        optimistic: 0.30
      p_otherwise:
        conservative: 0.00
        base: 0.05
        optimistic: 0.15
    event_overrides:
      open_close_window_minutes: 10
      set_mid_probability_to_zero: true
      specific_events:
        fomc:
          mid_acceptance_multiplier: 0.0
          spread_multiplier: 1.8
          latency_multiplier: 1.3
        opex:
          mid_acceptance_multiplier: 0.7
          spread_multiplier: 1.2
          latency_multiplier: 1.0

  optimistic:
    latency_ms: 150
    max_tob_participation: 0.12
    slippage_floor:
      per_contract: 0.015
      pct_of_spread: 0.06
    size_penalty:
      bp_per_extra_tob_multiple: 4
    adverse_selection_bps: 15
    mid_fill:
      p_when_spread_leq_20c:
        conservative: 0.00
        base: 0.15
        optimistic: 0.30
      p_otherwise:
        conservative: 0.00
        base: 0.05
        optimistic: 0.15
    event_overrides:
      open_close_window_minutes: 10
      set_mid_probability_to_zero: false
      specific_events:
        fomc:
          mid_acceptance_multiplier: 0.2
          spread_multiplier: 1.5
          latency_multiplier: 1.1
        opex:
          mid_acceptance_multiplier: 0.8
          spread_multiplier: 1.1
          latency_multiplier: 1.0